#! /bin/sh
set -e

#DEBHELPER#
if ! getent 'passwd' 'debianfdm' > /dev/null ; then
    adduser --quiet \
            --system \
            --no-create-home \
            --home /nonexistent \
            --disabled-login \
            --disabled-password \
            debianfdm
fi
exit 0
